baseURL = "https://progrrah.github.io/FilmShakirov/"
languageCode = "ru"
title = "FilmShakirov"
theme = "hugo-theme-stack"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  homeInfoParams = { Title = "Добрый день!", Content = "На этом сайте будут материалы, посвященные Ильгаму Шакирову." }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[menu]
[[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Фотолар"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Аудиолар"
  url = "/posts/"
  weight = 3

  [[menu.main]]
  name = "Хатлар"
  url = "/posts/"
  weight = 4

  [[menu.main]]
  name = "Хатлар"
  url = "/posts/"
  weight = 4

  